version: '3'
services:
  nginx:
    image: nginx:1.13
    container_name: nginx-https
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
